services:
  db:
    image: postgres:16
    container_name: referrals_db
    volumes:
      - postgresdata:/var/lib/postgresql/data
    env_file:
      - .env-non-dev
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=referrals
    ports:
      - 5432:5432

  referrals:
    image: referrals_app
    container_name: referrals_app
    build:
      context: .
    env_file:
      - .env-non-dev
    depends_on:
      - db
    command: >
      sh -c "sleep 10 && alembic upgrade head && gunicorn main:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"
    ports:
      - 7777:8000

volumes:
  postgresdata: